### ISSUE TITLE
Cache query with _near - improve handling instead of returning no data

### ISSUE THREAD

**Issue by alexbainbridge** [Kinvey/html5-sdk#10]
#### Steps to Reproduce
I have a search results (query) which currently HAS to be Kinvey.DataStoreType.Network, because it uses a location (_near) which only works on Network searches.

I then have a detail page which I would like to call using Kinvey.DataStoreType.Cache

Sadly this creates no results as cache doesn't respond with data, if there is nothing in the cache yet (however it does populate it for the next time around, which is nice actually) 

No bug here, its how its documented, but I have an improvement suggestion: 

#### Expected Result
I was thinking instead of me being forced to do Kinvey.DataStoreType.Network on my search results query (that uses _near) that I could

- query search using Kinvey.DataStoreType.Cache
- _near 
- Client library would actually run a Kinvey.DataStoreType.Network (so the _near works) and data is returned (only when _near is in the query) 
- data would save to local, so that first time in I would have data on a Kinvey.DataStoreType.Cache query or findById. 

i.e 
Kinvey.DataStoreType.Network & _near - return results and dont store in local cache?
Kinvey.DataStoreType.Cache & _near - return results (from Network) - and store in local cache

The documentation does say that the library is smart enough to work out what to do in different situations, so adding additional logic for doing a Network search when developer asks for _near and Cache would still be within the existing expectation that the library will determine what to do. 

#### Actual Result
If I search with Kinvey.DataStoreType.Cache & _near , the library returns no data. 

#### Version of Kinvey HTML5 SDK
kinvey-html5-sdk-3.3.4

#### NodeJS version
Not using Node, calling library from Cloudfront 

Without the above, I can work around it by having fall back queries for when I don't get a result but know one should exist..... but still, would be neater at library level!

**Comment by thomasconner** [comment]
Do you have a sample app using a `_near` in a query? If not I can create one but I thought I would ask.

**Comment by alexbainbridge** [comment]
I don't have a simple one handy sadly

Am I right though - if you use _near you MUST use Network?  (rather than Cache / Sync). Pretty sure the documentation used to say that (on the version 1 library, long time back) but now says you would only normally use Network within development..... so I am thinking I am perhaps wrong. 

And there is no way to get Network to also save to device, ready for a Cache or Sync usage subsequently. 

i.e. if you do a search (query) using Network and _near, and then want to get detail (FindById) using Cache, you can't. (unless you code additionally to handle an empty response on Cache when you know its really there)

**Comment by thomasconner** [comment]
I will write an update for this issue too soon. I believe we already support what you are asking about. Sorry about not responding on this issue for so long.

**Comment by alexbainbridge** [comment]
The fundamental question is how to get Network searches to save to device, ready for a subsequent cache search to use on the same collection.

If we can work that out, problem solved!

**Comment by thomasconner** [comment]
You would use the `pull()` function on a datastore.

```javascript
var store = Kinvey.DataStore.collection('books'. Kinvey.DataStoreType.Sync); // returns a Kinvey.DataStoreType.Cache by default
var query = new Query();
// Add filter for _near query
store.pull(query)
  .then(function(entities) {
    // Entities are from the network and stored locally in the cache 
  });
```

Please see http://devcenter.kinvey.com/html5/guides/datastore#Pull.

**Comment by alexbainbridge** [comment]
OK - will check soon. Needs to work with _geoloc which is the reason using a network search in the first place.... 

Thanks!

**Comment by thomasconner** [comment]
Geolocation queries do not work offline at this time however. We might look into adding support in the future but no plans at the moment have been made.

**Comment by alexbainbridge** [comment]
Yeah - this is why I have hit the problem. I just want data from a network (including _geoloc) search to go to device, so I can do a CACHE search later, that is NOT using _geoloc. I know a CACHE search later can't use _geoloc, thats fine) 

i.e. a network search that saves to device would do it

**Comment by thomasconner** [comment]
Ok sorry I misunderstood. What you are asking is possible and the information I shared above about the `pull()` function would do exactly what you are asking about.

**Comment by alexbainbridge** [comment]
Cool Thomas. Super. I built our prototype on v1 of Kinvey 2 years ago and I remember this problem on v1! (but solved that as the controls on this were slightly different)

**Comment by thomasconner** [comment]
Sounds good @alexbainbridge. I am going to close this issue. If you need to reopen please do so. Also if you need any help don't hesitate to reach out.
