### ISSUE TITLE
Docs - readpolicy - wrong example

### ISSUE THREAD

**Issue by alexbainbridge** [Kinvey/html5-sdk#11]
Looking at 
http://devcenter.kinvey.com/html5/guides/caching-offline

The readpolicy example currently is not the right example on the page above

```
// Create a Sync store
var dataStore = Kinvey.DataStore.collection('books', Kinvey.DataStoreType.Sync);
// Pull data from the backend and store it in your cache
dataStore.pull().then(function(entities) {
  // ...
}).catch(function(error) {
  // ...
});
```

Looking at e.g. the Angular JS example, its meant to be something like:

```
//create a Sync store
var dataStore = $kinvey.DataStore.getInstance('books', $kinvey.DataStoreType.Sync);
// Force the datastore to request data from the backend
dataStore.find(null, {
  readPolicy: $kinvey.ReadPolicy.ForceNetwork
}).then(function(entities) {
  ...
}).catch(function(error) {
  ...
});
```

**Comment by thomasconner** [comment]
@alexbainbridge Thanks for pointing this out. We will have the DevCenter guides update to show the correct code sample promptly. The first code sample you shared is the correct one. The three different store types `DataStoreType.Network`, `DataStoreType.Cache`, and `DataStoreType.Sync` are used to set the respective read policies.

**Comment by alexbainbridge** [comment]
Hi Thomas

Yeah - was trying to work out how to do **readPolicy: $kinvey.ReadPolicy.ForceNetwork** in HTML5

Thanks! Alex

**Comment by thomasconner** [comment]
This is how you would load your entities from the network and save them to the cache.

```javascript
var store = Kinvey.DataStore.collection('books', Kinvey.DataStoreType.Sync);
store.pull()
  .then(function(entities) {
    // entities were loaded from the network and saved to the cache
  })
  .catch(function(error) {
    // ...
  });
```

The `pull()` function also accepts a `Kinvey.Query` that can allow you to load a subset of the entities in your collection.

**Comment by alexbainbridge** [comment]
Ah, so the code example is right on HTML5, just the approach is different between the HTML5 library and the Angular one. Got it. 

ForceLocal, ForceNetwork, Both - that paragraph needs removing from the HTML5 docs?

**Comment by thomasconner** [comment]
Actually it is the same for Angular too. Yes that paragraph either needs to be removed or reworded.

**Comment by thomasconner** [comment]
This has been fixed in the latest release of the dev center guides.
